### ISSUE TITLE
am I doing something wrong?

### ISSUE THREAD

**Issue by dvvvsh** [dani69654/Script_GenerateMnem_Check_Balance#4]
jonathandoe@MacBook-Air script_generatemnem_check_balance % npm start

> script_generatemnem_check_balance@1.0.0 start
> node index.js

No Sendgrid API key found. This function is disabled.
API key does not start with "SG.".
/Users/jonathandoe/Script_GenerateMnem_Check_Balance/index.js:34
    throw new Error(error.message || error)
          ^

Error: Invalid provider
    at scan (/Users/jonathandoe/Script_GenerateMnem_Check_Balance/index.js:34:11)
    at Object.<anonymous> (/Users/jonathandoe/Script_GenerateMnem_Check_Balance/index.js:38:1)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.0.1
jonathandoe@MacBook-Air script_generatemnem_check_balance %

**Comment by dani69654** [comment]
My bad, fixing 5 mins

**Comment by dani69654** [comment]
The script is showing you the error `Error: Invalid provider`. <br>
This means that you did not set a `RPC provider` in the env file as per documentation (check readme.md). <br>
![image](https://user-images.githubusercontent.com/60792849/144240847-485181ab-6a36-4262-bc79-12b75359ee0f.png)

The `SENDGRID_API_KEY` is not mandatory but the provider is. <br>
Make sure to add a provider for Ethereum (Moralis offers speedy nodes, Infura offers RPC as well)
